task:
  name: rom
  timeout_in: 120m
  container:
    dockerfile: Dockerfile
    cpu: 8
    memory: 32G
  environment:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[2c5bb21245a42b7f5a0fb13d3229894e4b4397d2ecff63f89e34387d5a34d6e6a58a2319a723db9cb7b4ef9c5f500fa2]"
    TOKEN: "ENCRYPTED[a696f8a8c737caed23987978844adf83f4d9acf9cf788ca25ddbf9dab6b679472183e0879e95fee78681d018fc6089d6]"
    CHATID: "ENCRYPTED[ec610bb0cf01a7b9c4e8f56a5a5bca30f56df98695db16d2ac68f33e71c363589410e3d341134ba963746d1220da2d63]"
    BOTTOKEN: "ENCRYPTED[140e001cd10cd7036103b3503248c093742819267005a6e8b396c3914193483a9775873d758cb67995089d62ac0d62c5]"
    GIT_COOKIES: "ENCRYPTED[49d89d8e5cc6c0ab64075869aae63dce072cefad6f5724788c5d2fc67653d16623999a532ee4bfdff1a73874f4f25df0]"
    TDRIVE: "ENCRYPTED[83cd5edc31aa5c4e003730c99ac7bb0f74032f05689ed42ce104ee3400638c7b3a4a520f59b7aa2311dec50e5da233b5]"
    rom: "dotOS-Rc"
  download_ccache_background_script:
      - cd /tmp && mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - rclone copy brrbrr:ccache/$rom/ccache.tar.zst /tmp -P && tar -xaf ccache.tar.zst
  upload_ccache_background_script:
      - cd /tmp
      - while true; do sleep 95m; tar "-I zstd -1 -T8" -cf ccache.tar.zst ccache; rclone copy ccache.tar.zst brrbrr:ccache -P; rm ccache.tar.zst; done
  build_script:
      - bash build.sh
  final_upload_ccache_script:
      - cd /tmp && tar "-I zstd -1 -T8" -cf ccache.tar.zst ccache
      - rclone copy ccache.tar.zst brrbrr:ccache/$rom -P
